### ISSUE TITLE
Cannot Get Large Blob (size >= 128MB) on Azure Website (Basic, Large 4 cores, 7 GB, 1 Instance)

### ISSUE THREAD

**Issue by DeviLeo** [Azure/azure-sdk-for-php#729]
1. What am I doing
I am writing a php demo for uploading and downloading speed test on azure website.
See http://blobdemo.azurewebsites.net/DownloadBlobTest.php?filesize=128
This page will generate a file with specified size by provided parameter "filesize" in megabytes.
And then upload the file to Azure Storage Blob to determine the uploading speed from Azure Website to Azure Storage.
After finished uploading the file, it will downloading it to determine the downloading speed from Azure Storage to Azure Website.

2. Azure Website Scale
The scale of azure website for test is Basic (Large 4 cores, 7 GB), 1 instance.
PHP version is 5.4.

3. The Problem
When I uploading and downloading one file (size < 128MB), it seems OK.
But when I tried downloading a file (size >= 128MB), the error occurred.
I debugged the code and found the error happened at the function stringToStream in Utilities.php.
Stack Trace:
(4). "fopen('data://text/plain,' . urlencode($string), 'rb');", "function stringToStream($string)", "WindowsAzure\Common\Internal\Utilities.php";
(3). "$result->setContentStream(Utilities::stringToStream($body));", "function create($headers, $body, $metadata)", "WindowsAzure\Blob\Models\GetBlobResult.php";
(2). "return GetBlobResult::create($response->getHeader(), $response->getBody(), $metadata);", "function getBlob($container, $blob, $options = null)", "WindowsAzure\Blob\BlobRestProxy.php";
(1). "$blob = $blobRestProxy->getBlob($container, TEST_FILE);", "function download($filesize)", "DownloadBlobTest.php";

It seems downloading from Azure Storage is OK.
But error occurs at converting the data of large file (size >= 128MB) to stream.

**Comment by RobDonovan** [comment]
Hi,

What is the actual 'error' message you are getting?

A few things to think about....

Firstly, if the script is taking a while to run, then you might be timing out, rather than erroring. Easy to check by running it from the command prompt (using cli, as that removes the time limit, php.ini: max_execution_time)

You could be running out of memory allocated to php, check php.ini: memory_limit, default is 128M. But if that happened you should get an error message about it.

I'm currently having problems downloading 'large' files using the SDK. I dont get an error, but around the size of 128MB blobs, it starts taking a very long time to download. For example a 170MB takes 10 minutes, but a 100MB blob takes 1m:20s.

I think the reason for that, is memory, and I'm hitting the limit of the VM, and the VM starts swapping like crazy, making it very slow.

It seems the Azure PHP SDK is quite memory 'hungry' when downloading large blobs, using a max of 7x the blob size (depending on the blob contents/type).

For example, when I try to download a 100MB file, if I echo out memory_get_peak_usage() after the 
$blobRestProxy->getBlob() call, it says the peak was 700mb!.

Try putting this line in after your getBlob() command, and run it from the command prompt rather than the web. But since you said you have a 7GB machine, I would be surprised if you are hitting that limit though. I was using a 768mb VM, so I hit it pretty easily.

    echo "Peak memory usage: ", number_format(memory_get_peak_usage()), " bytes\n";

One reason so much memory seems to be used, is that fopen() line in untilities.php that you quoted. It is urlencoding the blob data, which if its a movie or something can easily treble the memory needed, and the fopen to a 'data://' uri seems to also use quite a bit of memory itself. So that line is the one that uses alot of memory, and could be the problem.

I think I've come to the point where I need to write my own api for accessing blobs, as this SDK seems a little to rough. I havent been able to get it to work with https and larger files and now I find this performance/memory usage is unacceptable for large blobs, atleast for me.

It seems the SDK is a bit 'dead' as there are little to no fixes being done, and no one seems to support it.

**Comment by RobDonovan** [comment]
I've done some testing with things, for memory and speed.

Tested on a Ubuntu (3.13.0-43-generic) VM, 1 CPU, 768mb Mem, php V5.5.9
450mb free memory, 2GB Swap assigned to /mnt/

I would expect the PHP SDK times to be better (but I'm not sure how much, and I cant spend more time on this spinning up another VM), if you upgraded the machine to more memory, as the problem I think is swapping, because the PHP SDK uses masses of memory. Might be interesting to see what you got with your 7GB machine.

PHP SDK seems to slow down exponentially, and starts using masses of memory, even for a blob only sized 240mb. Seems consistent with x7 the size of the blob.

2 scripts, first one uses the PHP SDK, 2nd one uses PHP CURL.

First file, 100MB video:
1st script: Runtime: 1m59s, Peak memory: 701,752,240 bytes
2nd script: Runtime: 0m13s, Peak memory: 240,096 bytes

Second file, 240MB video:
1st script: Runtime: 28m8s, Peak memory: 1,723,139,224 bytes
2nd script: Runtime: 0m34s, Peak memory: 240,040 bytes

*You need to change path/account/key/container/blobname variables to your own.

Run these direct from the command line.

Script1:

    <?php
    
    set_include_path('/home/system/www/phpLibs/azure'); // Set this to your azure PHP SDK path
    $account   = 'xxxx'; // Set this to your Azure Account name
    $key       = 'xxxx'; // Set this to your Azure Account Key
    $container = 'xxxx'; // Set this to your container
    $file      = 'xxxx'; // Set this to your blobname
    
    
    require_once "WindowsAzure/WindowsAzure.php";
    
    use WindowsAzure\Common\ServicesBuilder;
    use WindowsAzure\Common\ServiceException;
    
    $connectionString =  "DefaultEndpointsProtocol=http;AccountName=".$account.";AccountKey=".$key;
    
    $blobRestProxy = ServicesBuilder::getInstance()->createBlobService($connectionString);
    
    $blob = $blobRestProxy->getBlob($container, $file);
    $contents = stream_get_contents($blob->getContentStream());
    
    file_put_contents($file,$contents);
    
    echo 'Peak memory usage: ', number_format(memory_get_peak_usage()), " bytes\n";
    
    ?>

Script2:

    <?php
    
    define('AZURE_API_VERSION','2014-02-14');
    define('AZURE_PROTOCOL','https');
    define('AZURE_URL_FIXED','.blob.core.windows.net');
    
    define('AZURE_ACCOUNT',    'xxxx'); // Set this to your Azure Account name
    define('AZURE_ACCOUNT_KEY','xxxx'); // Set this to your Azure Account Key
    
    $container = 'xxxx'; // Set this to your container
    $blobName  = 'xxxx'; // Set this to your blobname
    
    
    $datetime = new DateTime('now',new DateTimeZone('GMT'));
    $now = $datetime->format('D, d M Y H:i:s') . ' GMT';
    
    $sig = array_fill(0,14,'');
    
    $sig[0] = 'GET';
    $sig[6] = $now;
    $sig[12] = 'x-ms-version:'.AZURE_API_VERSION;
    $sig[13] = '/'.AZURE_ACCOUNT.'/'.rawurlencode($container).'/'.rawurlencode($blobName);
    
    $signature = implode("\n",$sig);
    
    $authKey = 'SharedKey '.AZURE_ACCOUNT.':'.base64_encode(hash_hmac('sha256', $signature, base64_decode(AZURE_ACCOUNT_KEY), true));
    
    $url = AZURE_PROTOCOL.'://'.AZURE_ACCOUNT.AZURE_URL_FIXED.'/'.rawurlencode($container).'/'.rawurlencode($blobName);
    
    $fh = fopen($blobName, 'w');
    
    $ch = curl_init($url);
    
    curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
    curl_setopt($ch, CURLOPT_USERAGENT,'Azure PHP Tester');
    curl_setopt($ch, CURLOPT_FILE,$fh);
    
    curl_setopt($ch, CURLOPT_HTTPHEADER, array(
                            'x-ms-version:'.AZURE_API_VERSION,
                            'date:'.$now,
                            'authorization:'.$authKey));
    
    $ret = curl_exec($ch);
    
    if ($ret === false) {
            print $ret."\n";
    }
    
    echo ' Peak memory usage: ', number_format(memory_get_peak_usage()), " bytes\n";
    
    ?>

HTHs.

**Comment by DeviLeo** [comment]
Thank you, RobDonovan. You are right. I checked the log of Azure Website and found that the memory exhausted. The log said "PHP Fatal error:  Allowed memory size of 134217728 bytes exhausted (tried to allocate 132385096 bytes) in D:\home\site\wwwroot\vendor\pear-pear.php.net\HTTP_Request2\HTTP\Request2\Response.php on line 341".

I tried to modify the memory limit of php and iis. But unfortunately Azure Website is not like a VM and it has many restrictions. There is no option to change the memory limit and I have no way access php.ini and iis configuration. So the only thing I can do is to get rid of the sdk and write a function to download blob.

I tried the Script1 and Script2 on my pc, 2 CPUs, 2 GB memory, PHP 5.3.29. The Script1 which uses SDK consumed about 1 GB memory. And the Script2 which uses CURL consumed only 1 KB memory. That's awesome!

I have put the Script2 to the Azure Website. 
See http://blobdemo.azurewebsites.net/Script2.php
Now it can download 1 GB file and working very well.

RobDonovan, Thank you! You solved my problem!

**Comment by RobDonovan** [comment]
Glad it help you :)

As for php settings for IIS, have you looked that this: http://azure.microsoft.com/en-us/documentation/articles/web-sites-php-configure/

Looks like you might be able to use .user.ini files to set php settings maybe.

I only use *unix envs for web stuff, so I'm not that up on IIS stuff.

Also, you could try changing the memory limits within the script (then its just for that one script) with this at the beginning.

ini_set('memory_limit','200M');

**Comment by DeviLeo** [comment]
I have put the .user.ini into web root and it works. Also ini_set('memory_limit','200M');
But I think increasing the memory limit is not the best solution for me. Your Script2 is the best!

RobDonovan, thank you so much for great help!
