### ISSUE TITLE
nothing works 

### ISSUE THREAD

**Issue by avinashseth** [Azure/azure-sdk-for-php#738]
i'm a beginner with azure skd for php and i swear, this is one of the worst documentation i've ever seen, first i did the composer stuff and it didn't work, figured out, json file is wrong, got correct one on stackoverflow, somehow uploaded a blob, then figured out we have to set the content type, tried that but error Class 'CreateBlobOptions' not found, i mean seriously? there is no proper documentation, no proper guidance, no proper support for linux users too, please work it out, i'm not a single one, there are tons and tons of devs facing issue with azure. If you know please please make video, stop typing stuff on keyboard, record it too and start streaming it for god's sake

**Comment by ebuildy** [comment]
+1 !

Move to Amazon, their Php SDK is really really better, and just work as it should. Microsoft has never had a developper point of view.

**Comment by devigned** [comment]
@YuvalMazor please review this.

**Comment by YuvalMazor** [comment]
Hi @avinashseth.  I realize it's been a while since your comment and I'm sorry for the delay in responding.  We are going to be giving this project more attention going forward and would love to hear where you ran into problems with the azure php sdk.  Please feel free to ping me, @yaqiyang or @devigned and we will do our best to help you out and improve the experience.  Thanks.

**Comment by yaqiyang** [comment]
@avinashseth , the composer file has been fixed. If you have any problems or questions, please let us know.

Thanks
Yaqi

**Comment by yaqiyang** [comment]
Please reopen the issue if you get this problem again.

Thanks
Yaqi
