### ISSUE TITLE
Class not found

### ISSUE THREAD

**Issue by adityosnrost** [Azure/azure-sdk-for-php#790]
Hi,

I'm new on Azure SDK for PHP. I am trying on the example. I cannot run Media Service example:   vodworkflow_drm_playready_widevine.php  . The error said:

Fatal error: Class 'WindowsAzure\MediaServices\Templates\TokenType' not found in . . . 

I already follow all the guide on how to use SDK. My php included path are:
.:/usr/share/pear:/usr/share/php

Anyone can help me with this simple problem ?

Thanks

Best Regards,

Adityo Setyonugroho

**Comment by yaqiyang** [comment]
@adityosnrost , I will be glad to help you. Currently those types are only available if you use composer to get the dev build of the WindowsAzure project

**Comment by yaqiyang** [comment]
The composer entry should look like this, 
"require": {
        "microsoft/windowsazure": "0.4-dev"
      },     
After you got all dependencies, make sure folder vendor\microsoft\windowsazure\WindowsAzure\MediaServices\Templates exists. Also, you have to use PHP 5.5 and above for Media Services functions.

**Comment by yaqiyang** [comment]
[phptests.zip](https://github.com/Azure/azure-sdk-for-php/files/199952/phptests.zip)
I attached a completed working sample for vodworkflow_drm_playready_widevine.php. Unzip the file, update the following lines in vodworkflow_drm_playready_widevine.php,

$account = "your account";
$secret = "your secret";

then execute,
php vodworkflow_drm_playready_widevine.php. 

The video file will be uploaded and encoded in Azure.

Yaqi

**Comment by adityosnrost** [comment]
Hi @yaqiyang ,
Thanks a lot with your reply. So, any WindowsAzure SDK or packages on pear folder cannot be use yet ? And I need to use all WindowsAzure packages from composer ?

So if I must redo it from the start, is this the order : 

1. Clone the Git
2. Install HTTP_Request2, Mail_mime, and Mail_mimeDecode PEAR packages
3. Got all dependencies installed from composer for WindowsAzure SDK.
4. Then try the example from the clone.

is it right ?

Thank You

Best Regards,

Adityo Setyonugroho

**Comment by yaqiyang** [comment]
yes, use the packages from composer. We are moving away from the PEAR package manager. If you use the zip file I sent, you will already have all the dependencies and packages needed to run the sample. If you don't use it, just get the composer.phar and composer.json files out of it, run "php composer.phar install". It will install everything including the WindowsAzure SDK and all other packages. Basically, you don't need Steps 2 and 3, just need to run  "php composer.phar install". 

There is a bug with PHP 7.0 that prevents "php composer.phar install" to run successfully. So if you want to use PHP 7.x, you will need to use PHP 5.5+ to run this command. After the packages are installed, you can then you PHP 7.x to run the SDK code. 

yaqi

**Comment by yaqiyang** [comment]
@adityosnrost , is your problem resolved? Please close the issue if it is resolved. 

Thanks
Yaqi

**Comment by adityosnrost** [comment]
Hi @yaqiyang 

Sorry for my late reply. I was away for a couple days. I've tested it and it works like a charm :D. Thanks for your help, it was awesome. Btw, I had little question about .mp4 file. after I've finished upload, it show error like this:
The job has finished with a wrong status: Error 
But not with wmv file, any idea about that ? Thanks once again :)

**Comment by yaqiyang** [comment]
For the .mp4 file issue, I did try a small .mp4 file I downloaded from YouTube, and it worked well. Can you try a different mp4 file?
The first time I ran it, I did get the same error message ( "The job has finished with a wrong status: Error" ), but I when I looked up, I found "file_get_contents(test,mp4)" in the message. Basically, I had the wrong file name ( test,mp4, instead of test.mp4). 
-------------------------------------
d:\apps\phptests>php vodworkflow_drm_playready_widevine.php
Azure SDK for PHP - PlayReady + Widevine Dynamic Encryption Sample
Asset created: name=Mezzanine test,mp4 id=nb:cid:UUID:c0b704a1-08f0-4bf8-978f-cea7ca62cd87
PHP Warning: ** file_get_contents(test,mp4): failed to open stream: No such file or directory in D:\apps\phptests\vodworkflow_drm_playready_widevine.php on line 126
**
Warning: file_get_contents(test,mp4): failed to open stream: No such file or directory in D:\apps\phptests\vodworkflow_drm_playready_widevine.php on line 126
Uploading...
File uploaded: size=0
Using Media Processor: Media Encoder Standard version 1.1
Created Job with Id: nb:jid:UUID:0a3b27eb-8aa1-48a5-b987-d66110d8e4d8
Job status: Queued
Job status: Queued
Job status: Scheduled
Job status: Processing
Job status: Processing
Job status: Processing
Job status: Processing
Job status: Processing
Job status: Processing
The job has finished with a wrong status: Error

**Comment by yaqiyang** [comment]
For the .mp4 file issue, I did try a small .mp4 file I downloaded from YouTube, and it worked well. Can you try a different mp4 file?

The first time I ran it, I did get the same error message ( "The job has finished with a wrong status: Error" ), but I when I looked up, I found "file_get_contents(test,mp4)" in the message. Basically, I had the wrong file name ( test,mp4, instead of test.mp4). 

--------------------------------------
d:\apps\phptests>php vodworkflow_drm_playready_widevine.php
 Azure SDK for PHP - PlayReady + Widevine Dynamic Encryption Sample
 Asset created: name=Mezzanine test,mp4 id=nb:cid:UUID:c0b704a1-08f0-4bf8-978f-cea7ca62cd87
 PHP Warning: ** file_get_contents(test,mp4): failed to open stream: No such file or directory in D:\apps\phptests\vodworkflow_drm_playready_widevine.php on line 126

 Warning: file_get_contents(test,mp4): failed to open stream: No such file or directory in D:\apps\phptests\vodworkflow_drm_playready_widevine.php on line 126
 Uploading...
 File uploaded: size=0
 Using Media Processor: Media Encoder Standard version 1.1
 Created Job with Id: nb:jid:UUID:0a3b27eb-8aa1-48a5-b987-d66110d8e4d8
 Job status: Queued
 Job status: Queued
 Job status: Scheduled
 Job status: Processing
 Job status: Processing
 Job status: Processing
 Job status: Processing
 Job status: Processing
 Job status: Processing
 The job has finished with a wrong status: Error

**Comment by adityosnrost** [comment]
@yaqiyang 

Thanks for your reply.  I rechecked my code and I finally got it why my process was error. It was a full path on $mezzanineFileName. like this: $mezzanineFileName = "/home/user/video/test.mp4";
It cannot be done on encoding process.

it should be only the name of the file and the path should be inside file_get_contents("/home/user/video/" . $mezzanineFileName)

Thank you for reminding me of file name haha

Best Regards,

Adityo Setyonugroho
