### ISSUE TITLE
Is it possible to use this PHP SDK with SAS token?

### ISSUE THREAD

**Issue by maxwhale** [Azure/azure-sdk-for-php#856]
Hi all,

I experienced some difficulties to use this SDK with SAS token. Is it possible to use this SDK since we only receive the endpoint(URL) and SAS token, or this SDK doesn't support it. 

the sample code only shows ACS authentication method.

Thanks

**Comment by yaqiyang** [comment]
As far as I know, SAS is not support for service bus as this moment.

yaqi


On Aug 3, 2016, at 12:05 AM, Max <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi all,

I experienced some difficulties to use this SDK with SAS token. Is it possible to use this SDK since we only receive the endpoint(URL) and SAS token, or this SDK doesn't support it.

the sample code only shows ACS authentication method.

Thanks

**Comment by dr3dd** [comment]
Hi,
When i create Queue or Topic in Service Bus, i can create keys only SAS, I can not choose ACS, so SAS is support for Service Bus.
The Portla Azure create for me Connection string Endpoint=sb://{endpoint}.servicebus.windows.net/;SharedAccessKeyName={name};SharedAccessKey={key}=;EntityPath={entity} and this string not working in this SDK

**Comment by yaqiyang** [comment]
See this for information on this topic, https://github.com/Azure/azure-sdk-for-php#service-bus-queues

**Comment by maxwhale** [comment]
I have successfully published messages to topic via ACS authentication method, but i have a question regarding the returns. How do i know if a messages has been successfully published except 401, 403 those error messages? since I couldn't found anywhere in SDK defines the $result as successful or fail.

**Comment by maxwhale** [comment]
the problem was solved. the return is Message ID.

Thank you.
