### ISSUE TITLE
Is the ARM branch dead?

### ISSUE THREAD

**Issue by bedeMarkRadford** [Azure/azure-sdk-for-php#926]
My company is moving to ARM and we depend on the Service Bus.
Is this branch going to be resurrected?

Our proposed solution at the moment is to use REST and just make POST calls to the SB.

**Comment by sergey-shandar** [comment]
I'm working on ARM implementation of Azure SDK for PHP.

**Comment by sergey-shandar** [comment]
New ARM branch is https://github.com/Azure/azure-sdk-for-php/tree/arm2

**Comment by sergey-shandar** [comment]
@bedeMarkRadford you can try early preview from here https://packagist.org/packages/microsoft/windowsazure#dev-arm2

**Comment by phansys** [comment]
@sergey-shandar, is that branch intended to be part of a new release of this library (mean, `v2` by instance) or that branch is a release candidate for a new library?
My concerns are about the possibility to have both APIs working simultaneously, so I'd like to know which is the strategy you are proposing about this.
The solutions I think could be possible are:

1. Keep `0.x` and `1.x` branches as ASM compliant, while `2.x` branch drops support for ASM and adds support for ARM;
1. Keep `0.x` and `1.x` branches as ASM compliant, while `2.x` branch keeps (deprecated) support for ASM and adds support for ARM;
1. Keep all branches of this library as ASM compliant, and create a new library for ARM API.
I think the 2nd solution is currently the most convenient, since it could keep both APIs working, allowing to drop support for ASM from `3.x`.

Thank you in advance.
